/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LedController */

#ifndef _Included_LedController
#define _Included_LedController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     LedController
 * Method:    init
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_LedController_init
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     LedController
 * Method:    requestOutput
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_LedController_requestOutput
  (JNIEnv *, jobject);

/*
 * Class:     LedController
 * Method:    setOutput
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_LedController_setOutput
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     LedController
 * Method:    setBlinkOutput
 * Signature: (B)I
 */
JNIEXPORT jint JNICALL Java_LedController_setBlinkOutput
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     LedController
 * Method:    stopBlink
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_LedController_stopBlink
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
